services:
  app:
    build: .
    container_name: sensor-platform
    depends_on:
      mqtt:
        condition: service_healthy
      db:
        condition: service_healthy  
    environment:
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt-server
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./config/mosquitto/config:/mosquitto/config/
      - ./config/mosquitto/log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "test", "-C", "1"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./config/db/data:/var/lib/postgresql/data
      - ./config/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: myk_46
      POSTGRES_DB: sensor_platform
      POSTGRES_PASSWORD: myk_psdb
    healthcheck:
      test: ["CMD", "pg_isready",  "-U", "myk_46", "-d", "sensor_platform"]
      interval: 5s
      timeout: 5s
      retries: 5