platform:
  os: macOS
mqtt:
  username: matthew
  password: 1234
  port: 8883
  defaultValues: [1,2,3,4]
dniSensor:
  sunrise: 5 # in 24 hour time
  sunset: 18 # in 24 hour time
  minimumLimit: 0
  maximumLimit: 1100
  limitStep: 0.1
  stdDev: 10
logging:
  loggingPath: "/Users/matthew/dev/SensorPlatform/logs/"
  loggingInterval: 5